#!/usr/bin/env bash

# munin-pihole-plugins
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# shellcheck disable=SC2034,SC2086,SC2207

VERSION=06.05.02

_munin-pihole-plugins() {
    local cur allopts lolopts_help longopts longopts_help longopts_installuninstall opts_dnsserver opts_help opts_installuninstall opts_muninversion opts_variables prev prev2 shortopts shortopts_help shortopts_installuninstall
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    prev2="${COMP_WORDS[COMP_CWORD-2]}"
    case "${prev}" in
        "munin-pihole-plugins")
            allopts="-h help --help -i install --install -U uninstall --uninstall -V variables --variables -v version --version"
            longopts="--help --install --uninstall --variables --version"
            shortopts="-h -i -U -v -V"
            case "${cur}" in
                --*)
                    COMPREPLY=( $(compgen -W "${longopts}" -- ${cur}) )
                ;;
                -*)
                    COMPREPLY=( $(compgen -W "${shortopts}" -- ${cur}) )
                ;;
                *)
                    COMPREPLY=( $(compgen -W "${allopts}" -- ${cur}) )
            esac
        ;;
       "-h")
            shortopts_help="-h -i -U -V -v"
            if [[ "${prev2}" != *h ]]; then
                COMPREPLY=( $(compgen -W "${shortopts_help}" -- ${cur}) )
            fi
        ;;
        "help")
            opts_help="help install uninstall variables version"
            if [[ "${prev2}" != *help ]]; then
                COMPREPLY=( $(compgen -W "${opts_help}" -- ${cur}) )
            fi
        ;;
        "--help")
            lolopts_help="--I\\'ve-fallen-and-I-can\\'t-get-up"
            longopts_help="--help --install --uninstall --variables --version"
            if [[ "${prev2}" != *help ]]; then
                COMPREPLY=( $(compgen -W "${longopts_help}" -- ${cur}) )
            else
                COMPREPLY=( $(compgen -W "${lolopts_help}" -- ${cur}) )
            fi
        ;;
        "-i"|"-U")
            shortopts_installuninstall="-p -P -s -S -w -W"
            COMPREPLY=( $(compgen -W "${shortopts_installuninstall}" -- ${cur}) )
        ;;
        "install"|"uninstall")
            opts_installuninstall="plugins plugins-only script script-only webserver webserver-only"
            COMPREPLY=( $(compgen -W "${opts_installuninstall}" -- ${cur}) )
        ;;
        "--install"|"--uninstall")
            longopts_installuninstall="--plugins --plugins-only --script --script-only --webserver --webserver-only"
            COMPREPLY=( $(compgen -W "${longopts_installuninstall}" -- ${cur}) )
        ;;
        "-V"|"variables"|"--variables")
            opts_variables="BRANCH DNS_PORT DNS_SERVER INSTALL_PLUGINS INSTALL_SCRIPT INSTALL_WEBSERVER MUNIN_DIR MUNIN_CONFIG_DIR MUNIN_PLUGIN_DIR NODE_PLUGIN_DIR PLUGIN_CONFIG_DIR PLUGIN_LIST PROXY_CONFIG_DIR SCRIPT_DIR SHOW_COLOR SKIP_DEPENDENCY_CHECK UPDATE_SELF VERBOSITY_LEVEL"
            if [[ "${prev2}" != *h ]]; then
                COMPREPLY=( $(compgen -W "${opts_variables}" -- ${cur}) )
            fi
        ;;
        "BRANCH"|"DNS_PORT"|"INSTALL_PLUGINS"|"INSTALL_SCRIPT"|"INSTALL_WEBSERVER"|"MUNIN_DIR"|"MUNIN_CONFIG_DIR"|"MUNIN_PLUGIN_DIR"|"NODE_PLUGIN_DIR"|"PLUGIN_CONFIG_DIR"|"PLUGIN_LIST"|"PROXY_CONFIG_DIR"|"SCRIPT_DIR"|"SHOW_COLOR"|"SKIP_DEPENDENCY_CHECK"|"UPDATE_SELF"|"VERBOSITY_LEVEL")
            if [[ "${prev2}" == "-V" ]] || [[ "${prev2}" == "variables" ]] || [[ "${prev2}" == "--variables" ]]; then
                COMPREPLY=( $(compgen -W "RESET" -- ${cur}) )
            fi
        ;;
        "DNS_SERVER")
            opts_dnsserver="CLOUDFLARE COMODO GOOGLE LOCALHOST QUAD9 RESET"
            if [[ "${prev2}" == "-V" ]] || [[ "${prev2}" == "variables" ]] || [[ "${prev2}" == "--variables" ]]; then
                COMPREPLY=( $(compgen -W "${opts_dnsserver}" -- ${cur}) )
            fi
        ;;
        "MUNIN_VERSION")
            opts_muninversion="latest stable"
            if [[ "${prev2}" == "-V" ]] || [[ "${prev2}" == "variables" ]] || [[ "${prev2}" == "--variables" ]]; then
                COMPREPLY=( $(compgen -W "${opts_muninversion}" -- ${cur}) )
            fi
        ;;
        *)
        return 1
        ;;
    esac
    return 0
}
complete -F _munin-pihole-plugins munin-pihole-plugins
