#!/usr/bin/env bash

# munin-pihole-plugins
# saint-lascivious (Hayden Pearce) ©2022

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# Contact: munin-pihole-plugins@sainternet.xyz

# munin-pihole-plugins version
# must follow 8 character major.minor.micro scheme
# shellcheck disable=SC2034
VERSION="07.27.00"

# shellcheck disable=SC2207
_munin-pihole-plugins() {
    local cur allopts lolopts_help longopts longopts_installuninstall \
        longopts_restart longopts_show opts_branch opts_dnsserver opts \
        opts_holdduration opts_installuninstall opts_muninbranch opts_restart \
        opts_show opts_truefalse opts_variables opts_verbositylevel prev \
        prev2 shortopts shortopts_installuninstall shortopts_restart \
        shortopts_show
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    allopts="-c configure --configure -d debug --debug -h help --help -i \
        install --install -r restart --restart -s show --show -u uninstall \
        --uninstall -v version --version"
    longopts="--configure --debug --help --install --restart --show \
        --uninstall --version"
    longopts_installuninstall="--plugins --plugins-only --script --script-only \
        --webserver --webserver-only"
    longopts_restart"--plugins --webserver"
    longopts_show="--conditions --gnu-gpl --liability --warranty"
    opts="configure debug help install show uninstall version"
    opts_branch="development master RESET"
    opts_holdduration="0 1 2 3 4 5 RESET"
    opts_installuninstall="plugins plugins-only script script-only webserver \
        webserver-only"
    opts_dnsserver="CLOUDFLARE COMODO GOOGLE LOCALHOST QUAD9 RESET"
    opts_muninbranch="latest stable"
    opts_restart="plugins webserver"
    opts_show="conditions gnu-gpl liability warranty"
    opts_truefalse="true false RESET"
    opts_variables="BRANCH DNS_PORT DNS_SERVER HOLD_DURATION \
        IGNORE_PIHOLE_ON_HOST INSTALL_PLUGINS INSTALL_SCRIPT LIGHTTPD_WEBROOT \
        INSTALL_WEBSERVER MUNIN_BRANCH MUNIN_DIR MUNIN_CONFIG_DIR \
        MUNIN_PLUGIN_DIR NODE_PLUGIN_DIR PLUGIN_CONFIG_DIR PLUGIN_LIST \
        PROXY_CONFIG_DIR SCRIPT_DIR SHOW_COLOUR SHOW_HEADER \
        SKIP_DEPENDENCY_CHECK UPDATE_SELF VERBOSITY_LEVEL"
    opts_verbositylevel="0 1 2 3 4 RESET"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    prev2="${COMP_WORDS[COMP_CWORD-2]}"
    shortopts="-c -d -h -i -r -s -u -v"
    shortopts_installuninstall="-p -P -s -S -w -W"
    shortopts_restart"-p -w"
    shortopts_show="-c -g -l -w"
    case "${prev}" in
        "munin-pihole-plugins")
            case "${cur}" in
                --*)
                    COMPREPLY=( $(compgen -W "${longopts}" -- "${cur}") )
                ;;
                -*)
                    COMPREPLY=( $(compgen -W "${shortopts} ${longopts}" -- "${cur}") )
                ;;
                *)
                    COMPREPLY=( $(compgen -W "${allopts}" -- "${cur}") )
            esac
        ;;
        "-c"|"configure"|"--configure")
            if [[ "${prev2}" != "-h" ]] && [[ "${prev2}" != "help" ]] && [[ "${prev2}" != "--help" ]]; then
                COMPREPLY=( $(compgen -W "${opts_variables}" -- "${cur}") )
            fi
        ;;
       "-h")
            if [[ "${prev2}" != "-h" ]] && [[ "${prev2}" != "help" ]] && [[ "${prev2}" != "--help" ]]; then
                COMPREPLY=( $(compgen -W "${shortopts} ${longopts}" -- "${cur}") )
            fi
        ;;
        "help")
            if [[ "${prev2}" != "-h" ]] && [[ "${prev2}" != "help" ]] && [[ "${prev2}" != "--help" ]]; then
                COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
            fi
        ;;
        "--help")
            if [[ "${prev2}" != "-h" ]] && [[ "${prev2}" != "help" ]] && [[ "${prev2}" != "--help" ]]; then
                COMPREPLY=( $(compgen -W "${longopts}" -- "${cur}") )
            else
                lolopts_help="--i\\'ve-fallen-and-i-can\\'t-get-up"
                COMPREPLY=( $(compgen -W "${lolopts_help}" -- "${cur}") )
            fi
        ;;
        "-i"|"-u")
            COMPREPLY=( $(compgen -W "${shortopts_installuninstall} ${longopts_installuninstall}" -- "${cur}") )
        ;;
        "-r")
            COMPREPLY=( $(compgen -W "${shortopts_restart} ${longopts_restart}" -- "${cur}") )
        ;;
        "-s")
            COMPREPLY=( $(compgen -W "${shortopts_show} ${longopts_show}" -- "${cur}") )
        ;;
        "install"|"uninstall")
            COMPREPLY=( $(compgen -W "${opts_installuninstall}" -- "${cur}") )
        ;;
        "restart")
            COMPREPLY=( $(compgen -W "${opts_restart}" -- "${cur}") )
        ;;
        "show")
            COMPREPLY=( $(compgen -W "${opts_show}" -- "${cur}") )
        ;;
        "--install"|"--uninstall")
            COMPREPLY=( $(compgen -W "${longopts_installuninstall}" -- "${cur}") )
        ;;
        "--restart")
            COMPREPLY=( $(compgen -W "${longopts_restart}" -- "${cur}") )
        ;;
        "--show")
            COMPREPLY=( $(compgen -W "${longopts_show}" -- "${cur}") )
        ;;
        "BRANCH")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_branch}" -- "${cur}") )
            fi
        ;;
        "DNS_PORT"|"EXTERNAL_CONFIG_DIR"|"EXTERNAL_CONFIG_FILE"|"MUNIN_DIR"|"MUNIN_CONFIG_DIR"|"MUNIN_PLUGIN_DIR"|"NODE_PLUGIN_DIR"|"PLUGIN_CONFIG_DIR"|"PLUGIN_LIST"|"PROXY_CONFIG_DIR"|"SCRIPT_DIR")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "RESET" -- "${cur}") )
            fi
        ;;
        "DNS_SERVER")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_dnsserver}" -- "${cur}") )
            fi
        ;;
        "HOLD_DURATION")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_holdduration}" -- "${cur}") )
            fi
        ;;
        "IGNORE_PIHOLE_ON_HOST"|"INSTALL_PLUGINS"|"INSTALL_SCRIPT"|"INSTALL_WEBSERVER"|"SHOW_COLOR"|"SHOW_COLOUR"|"SHOW_HEADER"|"SKIP_DEPENDENCY_CHECK"|"UPDATE_SELF")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_truefalse}" -- "${cur}") )
            fi
        ;;
        "MUNIN_BRANCH")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_muninbranch}" -- "${cur}") )
            fi
        ;;
        "VERBOSITY_LEVEL")
            if [[ "${prev2}" == "-c" ]] || [[ "${prev2}" == "configure" ]] || [[ "${prev2}" == "--configure" ]]; then
                COMPREPLY=( $(compgen -W "${opts_verbositylevel}" -- "${cur}") )
            fi
        ;;
        *)
            return 1
        ;;
    esac
    return 0
}

complete -F _munin-pihole-plugins munin-pihole-plugins
