#!/bin/sh

# A Munin plugin to monitor Pi-hole, part of munin-pihole-plugins

# Environment variables for this script
#
#     host      - Pi-hole host address
#     port      - Pi-hole web interface port
#     api       - Pi-hole API query path
#
# You can set them in your munin/plugin-conf.d/plugins.conf file with:
#
# [pihole_*]
#     user root
#     env.host 127.0.0.1
#     env.port 80
#     env.api /admin/api.php

envhost=${host:-127.0.0.1}
envport=${port:-80}
envapi=${api:-/admin/api.php}

apicall=$(curl -s "$envhost:$envport$envapi" 2>/dev/null)
stats=$(echo $apicall | sed 's/[{}"]//g' | tr "," "\n")

case $1 in
  config)
    echo "graph_title Pi-hole Status"
    echo "graph_args --base 1000 -l -1 -u 1"
    echo "graph_vlabel offline / disabled / enabled"
    echo "graph_scale no"
    echo "graph_category pi-hole"
    echo "graph_info This graph shows statistics on Pi-hole's blocking status."

    for stat in $stats
    do
        uid=$(echo $stat | sed 's/:.*//')
        if [ $uid = "status" ]; then
            echo "$uid.label blocking status"
            echo "$uid.type GAUGE"
            echo "$uid.min 0"
        fi
    done

  exit 0;;
esac

for stat in $stats
do
    uid=$(echo $stat | sed 's/:.*//')
    if [ $uid = "status" ]; then
        value=$(echo $stat | sed 's/.*://')
        if [ $value = "enabled" ]; then
            echo "$uid.value 1"
        else
            if [ $value = "disabled" ]; then
                echo "$uid.value 0"
            else
                echo "$uid.value -1"
            fi
        fi
    fi
done
