#!/bin/sh

# A Munin plugin to monitor Pi-hole, part of munin-pihole-plugins

# Environment variables for this script
#
#     host          - Pi-hole host address
#     port          - Pi-hole web interface port
#     api           - Pi-hole API query path
#     cachesuffix   - Pi-hole API query cache info suffix
#     webpassword   - Pi-hole setupVars.conf WEBPASSWORD value
#
# You can set them in your munin/plugin-conf.d/plugins.conf file with:
#
# [pihole_*]
#     user root
#     env.host 127.0.0.1
#     env.port 80
#     env.api /admin/api.php
#     env.cachesuffix ?getCacheInfo&auth=
#     env.webpassword PIHOLE_SETUPVARS_WEBPASSWORD_HERE

setupvars="/etc/pihole/setupVars.conf"
get_webpassword="$(cat $setupvars | grep WEBPASSWORD | sed s/WEBPASSWORD=//g)"

envhost=${host:-127.0.0.1}
envport=${port:-80}
envapi=${api:-/admin/api.php}
envcachesuffix=${cachesuffix:-?getCacheInfo&auth=}
envwebpassword=${webpassword:-$get_webpassword}

apicall=$(curl -s "$envhost:$envport$envapi$envcachesuffix$envwebpassword" 2>/dev/null)
stats=$(echo $apicall | sed 's/[{}"]//g' | tr "," "\n")

case $1 in
  config)
    echo "graph_title Pi-hole Cache Info"
    echo "graph_args --base 1000 -l 0"
    echo "graph_vlabel cache packets"
    echo "graph_scale no"
    echo "graph_category pi-hole"
    echo "graph_info This graph shows statistics on Pi-hole cache contents."

    for stat in $stats
    do
        uid=$(echo $stat | sed 's/:.*//')
        if [ $uid = "cache-live-freed" ] || [ $uid = "cache-inserted" ] || [ $uid = "ip4" ] || [ $uid = "ip6" ] || [ $uid = "srv" ] || [ $uid = "cname" ] || [ $uid = "ds" ] || [ $uid = "dnskey" ] || [ $uid = "other" ] || [ $uid = "expired" ] || [ $uid = "immortal" ]; then
            echo "$uid.label $uid"
            echo "$uid.type GAUGE"
            echo "$uid.min 0"
        fi
    done

  exit 0;;
esac

for stat in $stats
do
    uid=$(echo $stat | sed 's/:.*//')
    if [ $uid = "cache-live-freed" ] || [ $uid = "cache-inserted" ] || [ $uid = "ip4" ] || [ $uid = "ip6" ] || [ $uid = "srv" ] || [ $uid = "cname" ] || [ $uid = "ds" ] || [ $uid = "dnskey" ] || [ $uid = "other" ] || [ $uid = "expired" ] || [ $uid = "immortal" ]; then
        value=$(echo $stat | sed 's/.*://')
        echo "$uid.value $value"
    fi
done
