#!/bin/sh

# A Munin plugin to monitor Pi-hole, part of munin-pihole-plugins

# Environment variables for this script
#
#     host      - Pi-hole host address
#     port      - Pi-hole web interface port
#     api       - Pi-hole API query path
#
# You can set them in your munin/plugin-conf.d/plugins.conf file with:
#
# [pihole_*]
#     user root
#     env.host 127.0.0.1
#     env.port 80
#     env.api /admin/api.php

envhost=${host:-127.0.0.1}
envport=${port:-80}
envapi=${api:-/admin/api.php}

apicall=$(curl -s "$envhost:$envport$envapi" 2>/dev/null)
stats=$(echo "$apicall" | sed 's/[{}"]//g' | tr "," "\\n")

case $1 in
  config)
    echo "graph_title Pi-hole clients"
    echo "graph_args --base 1000 -l 0"
    echo "graph_vlabel number of clients"
    echo "graph_scale no"
    echo "graph_category dns"
    echo "graph_info This graph shows clients seen by Pi-hole, both current and all time."

    for stat in $stats
    do
        uid=$(echo "$stat" | sed 's/:.*//')
        if [ "$uid" = "unique_clients" ] || [ "$uid" = "clients_ever_seen" ]; then
            echo "$uid.label $(echo "$uid" | sed 's/_/ /g')"
            echo "$uid.min 0"
        fi
    done

  exit 0;;
esac

for stat in $stats
do
    uid=$(echo "$stat" | sed 's/:.*//')
    if [ "$uid" = "unique_clients" ] || [ "$uid" = "clients_ever_seen" ]; then
        value=$(echo "$stat" | sed 's/.*://')
        echo "$uid.value $value"
    fi
done
