#!/bin/sh

######THIS PLUGIN IS DEPRECATED!######
#                                    #
# Use the monolithic plugin, pihole_ #
#                                    #
######################################

# munin-pihole-plugins - percent
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# Environment variables for this script
#
#     host      - Pi-hole host address
#     port      - Pi-hole web interface port
#     api       - Pi-hole API query path
#
# You can set them in your munin/plugin-conf.d/plugins.conf file with:
#
# [pihole_*]
#     user root
#     env.host 127.0.0.1
#     env.port 80
#     env.api /admin/api.php

envhost="${host:-127.0.0.1}"
envport="${port:-80}"
envapi="${api:-/admin/api.php}"

apicall="$(curl -sL "$envhost:$envport$envapi" 2>/dev/null)"
stats="$(echo "$apicall" | sed 's/[{}"]//g' | tr "," "\\n")"

case $1 in
    config)
        echo "graph_title Pi-hole blocked query percent"
        echo "graph_args --base 1000 -l 0 -u 100"
        echo "graph_vlabel percent blocked"
        echo "graph_scale no"
        echo "graph_category dns"
        echo "graph_info This graph shows Pi-hole's blocked query percentage."
        for stat in $stats; do
            uid="$(echo "$stat" | sed 's/:.*//')"
            if [ "$uid" = "ads_percentage_today" ]; then
                echo "$uid.label percentage blocked"
                echo "$uid.type GAUGE"
                echo "$uid.min 0"
            fi
        done
    exit 0;;
esac

for stat in $stats; do
    uid="$(echo "$stat" | sed 's/:.*//')"
    if [ "$uid" = "ads_percentage_today" ]; then
        value="$(echo "$stat" | sed 's/.*://')"
        echo "$uid.value $value"
    fi
done
