#!/bin/sh

# munin-pihole-plugins - queries
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# Environment variables for this script
#
#     host      - Pi-hole host address
#     port      - Pi-hole web interface port
#     api       - Pi-hole API query path
#
# You can set them in your munin/plugin-conf.d/plugins.conf file with:
#
# [pihole_*]
#     user root
#     env.host 127.0.0.1
#     env.port 80
#     env.api /admin/api.php

envhost="${host:-127.0.0.1}"
envport="${port:-80}"
envapi="${api:-/admin/api.php}"

apicall="$(curl -sL "$envhost:$envport$envapi" 2>/dev/null)"
stats="$(echo "$apicall" | sed 's/[{}"]//g' | tr "," "\\n")"

case $1 in
    config)
        echo "graph_title Pi-hole queries"
        echo "graph_args --base 1000 -l 0"
        echo "graph_vlabel queries"
        echo "graph_scale no"
        echo "graph_category dns"
        echo "graph_info This graph shows statistics on queries seen by Pi-hole."
        for stat in $stats; do
            uid="$(echo "$stat" | sed 's/:.*//')"
            if [ "$uid" = "dns_queries_today" ] || [ "$uid" = "ads_blocked_today" ] || [ "$uid" = "queries_forwarded" ] || [ "$uid" = "queries_cached" ]; then
                echo "$uid.label $(echo "$uid" | sed 's/dns_queries_today/queries/; s/ads_blocked_today/blocked queries/; s/queries_//')"
                echo "$uid.type GAUGE"
                echo "$uid.min 0"
            fi
        done
    exit 0;;
esac

for stat in $stats; do
    uid="$(echo "$stat" | sed 's/:.*//')"
    if [ "$uid" = "dns_queries_today" ] || [ "$uid" = "ads_blocked_today" ] || [ "$uid" = "queries_forwarded" ] || [ "$uid" = "queries_cached" ]; then
        value="$(echo "$stat" | sed 's/.*://')"
        echo "$uid.value $value"
    fi
done
