#!/usr/bin/env bash

# munin-pihole-plugins
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# munin-pihole-plugins version
# must follow 8 character major.minor.micro scheme
VERSION="05.00.00"

# environment variables with overrides
dns_port="${DNS_PORT:-53}"
dns_server="${DNS_SERVER:-208.67.222.222}"
install_plugins="${INSTALL_PLUGINS:-true}"
install_script="${INSTALL_SCRIPT:-true}"
install_webserver="${INSTALL_WEBSERVER:-true}"
munin_dir="${MUNIN_DIR:-/etc/munin}"
munin_config_dir="${MUNIN_CONFIG_DIR:-$munin_dir/munin-conf.d}"
munin_plugin_dir="${MUNIN_PLUGIN_DIR:-/usr/share/munin/plugins}"
node_plugin_dir="${NODE_PLUGIN_DIR:-$munin_dir/plugins}"
plugin_config_dir="${PLUGIN_CONFIG_DIR:-$munin_dir/plugin-conf.d}"
plugin_list="${PLUGIN_LIST:-blocked cache cache_by_type clients percent queries replies_by_type status unique_domains}"
proxy_config_dir="${PROXY_CONFIG_DIR:-/etc/lighttpd}"
script_dir="${SCRIPT_DIR:-/usr/local/bin}"
skip_dependency_check="${SKIP_DEPENDENCY_CHECK:-false}"
update_self="${UPDATE_SELF:-true}"
verbose_output="${VERBOSE_OUTPUT:-true}"

# environment variables without
current_directory="$(dirname "$(readlink -f "$0")")"
plugin_dependencies="curl munin-node "
plugin_repo="https://raw.githubusercontent.com/saint-lascivious/munin-pihole-plugins/development"
plugin_services="munin-node "
proxy_repo="https://raw.githubusercontent.com/saint-lascivious/lighttpd-external-munin-proxy/master"
script_dependencies="init-system-helpers wget "
terminal_height="$(stty size | cut -d " " -f1)"
terminal_width="$(stty size | cut -d " " -f2)"
webserver_dependencies="lighttpd munin "
webserver_services="lighttpd munin "

# simple privilege check
check_privilege() {
    if [[ ! "$EUID" -eq "0" ]];then
        if [[ -x "$(command -v sudo)" ]]; then
            exec sudo -E bash "$0" "$@"
            exit "$?"
        else
            echo -e " * \\e[31;1m[ERROR]\\e[0m Insufficient privileges
   Install sudo or run munin-pihole-plugins as root"
        exit 1
        fi
    fi
}

# there are ways of doing this without spawning a child script
# but they all suck, and/or are extremely convoluted
# this approach is a tradeoff
update_script() {
    cat > "$TEMP/.munin-pihole-plugins_update" << EOF
#!/usr/bin/env bash

# .munin-pihole-plugins_update
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# a simple you self update function for the munin-pihole-plugins script
update_now() {
    if [[ -x "$(command -v wget)" ]]; then
        wget -q --show-progress munin-pihole-plugins.sainternet.xyz -O "$current_directory/munin-pihole-plugins"
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m The required command 'wget' was not found"
        exit 1
    fi
    chmod +x "$current_directory/munin-pihole-plugins" || return
    echo -e " * \\e[32;1m[INFO]\\e[0m Restarting after update"
    exec env UPDATE_SELF="false" /bin/bash "$0" "$@"
}

update_now
EOF
    chmod +x "$TEMP/.munin-pihole-plugins_update"
    echo -e " * \\e[32;1m[INFO]\\e[0m Updating munin-pihole-plugins"
    exec /bin/bash "$TEMP/.munin-pihole-plugins_update"
}

# echo wrapper to handle verbosity
# if verbose_output is set to any value other than true only error messages
# are shown
output() {
    if [ "$verbose_output" == "true" ]; then
      echo -e "$@"
    fi
}

# manditory horrific ascii header
obnoxious_header() {
    if [[ "$terminal_height" -ge "6" ]] && [[ "$terminal_width" -ge "80" ]]; then
        output "\\e[31;1m                  _             _ _        _            _           _ v$VERSION
\\e[33;1m   _ __ _  _ _ _ (_)_ _ __ _ __(_) |_  ___| |___ _ _ __| |_  _ __ _(_)_ _  ___
\\e[32;1m  | '  \\ || | ' \\| | ' \\__| '_ \\ | ' \\/ _ \\ / -_)_| '_ \\ | || / _\` | | ' \\(_-<
\\e[34;1m  |_|_|_\\_,_|_||_|_|_||_| | .__/_|_||_\\___/_\\___| | .__/_|\\_,_\\__, |_|_||_/__/
\\e[36;1m                          |_|                     |_|         |___/
\\e[35;1m Munin plugins and management script for monitoring various Pi-hole® statistics\\e[0m"
    fi
}

# is this a pihole host?
check_pihole() {
    if [[ ! -x "$(command -v pihole)" ]]; then
        pihole_on_host="no"
    fi
}

# basic dependency handling with dpkg-query and apt
# can be disabled with SKIP_DEPENDENCY_CHECK set to any value other than false
install_dependencies() {
    if [[ "$install_plugins" == "true" ]]; then
        dependency_list+="$plugin_dependencies"
    fi
    if [[ "$install_script" == "true" ]]; then
        dependency_list+="$script_dependencies"
    fi
    if [[ "$install_webserver" == "true" ]]; then
        dependency_list+="$webserver_dependencies"
    fi
    if [[ -x "$(command -v dpkg-query)" ]]; then
        if [[ -x "$(command -v apt)" ]]; then
            output " * \\e[32;1m[INFO]\\e[0m Checking dependencies"
            for dependency_id in $dependency_list; do
                package_query="$(dpkg-query -W --showformat='${Status}\n' "$dependency_id" | grep "install ok installed")"
                if [[ -n "$package_query" ]]; then
                    output "   $dependency_id found"
                else
                    apt install "$dependency_id"
                fi
            done
        else
            echo -e " * \\e[31;1m[ERROR]\\e[0m The required command 'apt' was not found"
            exit 1
        fi
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m The required command 'dpkg-query' was not found"
        exit 1
    fi
}

# creatively named wget wrapper
# wget output hinges on verbose_output being set to 'true' (default)
download() {
    if [[ -x "$(command -v wget)" ]]; then
        if [[ "$verbose_output" == "true" ]]; then
            wget -q --show-progress "$@"
        else
            wget -q "$@"
        fi
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m The required command 'wget' was not found"
        exit 1
    fi
}

# installs a related project lighttpd-external-munin-proxy
# backup any existing non-zero lighttpd external.conf if no backup exists
# safely merging any existing external.conf properties without conflict
# would be tedious and annoying, and is out of scope at this point
configure_proxy() {
    proxy_config="$proxy_config_dir/external.conf"
    if [[ -d "$proxy_config_dir" ]]; then
        if [[ -s "$proxy_config" ]]; then
            if [[ ! -f "$proxy_config.orig" ]]; then
                mv "$proxy_config" "$proxy_config.orig" || return
                output " * \\e[32;1m[INFO]\\e[0m Existing lighttpd external.conf backed up to
   $proxy_config.orig"
            fi
        fi
        output " * \\e[32;1m[INFO]\\e[0m Installing Munin webserver proxy configuration"
        download "$proxy_repo/etc/lighttpd/external.conf" -O "$proxy_config"
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m No lighttpd configuration directory found at
   $proxy_config_dir"
        output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export PROXY_CONFIG_DIR=\"/path/to/directory\""
        exit 1
    fi
}

# configure the munin monitoring environment
# two different approaches may be used to set the graph strategy depending on
# the existence of the munin_config_dir
# if it is not found munin-pihole-plugins aill attempt to edit the munin.conf
# file directly
configure_munin() {
    if [[ -d "$munin_config_dir" ]]; then
        if [[ ! -f "$munin_config_dir/99-graph-strategy.conf" ]]; then
            output " * \\e[32;1m[INFO]\\e[0m Installing Munin server graph strategy configuration"
            download "$plugin_repo/etc/munin/munin-conf.d/99-graph-strategy.conf" -P "$munin_config_dir" || return
        fi
    else
        output " * \\e[32;1m[INFO]\\e[0m Attempting fallback configuration editing munin.conf directly"
        if [[ -d "$munin_dir" ]]; then
            if [[ -f "$munin_dir/munin.conf" ]]; then
                sed -i "s/^#html_strategy cron/html_strategy cgi/g" "$munin_dir/munin.conf" || return
                sed -i "s/^#graph_strategy cron/graph_strategy cgi/g" "$munin_dir/munin.conf" || return
            else
                echo -e " * \\e[31;1m[ERROR]\\e[0m No munin.conf file found at
   $munin_dir/munin.conf"
                output " * \\e[32;1m[INFO]\\e[0m If this file is located at a different path try
   export MUNIN_DIR=\"/path/to/directory\""
                exit 1
            fi
        else
            echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin directory found at
   $munin_dir"
            output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export MUNIN_DIR=\"/path/to/directory\""
            exit 1
        fi
        echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin configuration directory found at
   $munin_config_dir"
        output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export MUNIN_CONFIG_DIR=\"/path/to/directory\""
        exit 1
    fi
}

# remove all existing munin-pihole-plugins plugins and symbolic links
# munin will reap abandoned plugin .rrd files itself
# retain removal of legacy plugins instead of abandoning them while
# switching from individual plugins to the monolithic plugin
uninstall_plugins() {
    all_plugins="blocked cache cache_by_type clients percent queries replies_by_type status unique_domains"
    if [[ -d "$munin_plugin_dir" ]]; then
        if [[ -f "munin_plugin_dir/pihole_" ]]; then
            rm "munin_plugin_dir/pihole_" || return
        fi
        for plugin_id in $all_plugins; do
            if [[ -f "$munin_plugin_dir/pihole_$plugin_id" ]]; then
                rm "$munin_plugin_dir/pihole_$plugin_id" || return
            fi
        done
    fi
    if [[ -d "$node_plugin_dir" ]]; then
        for plugin_id in $all_plugins; do
            if [[ -h "$node_plugin_dir/pihole_$plugin_id" ]]; then
                rm "$node_plugin_dir/pihole_$plugin_id" || return
            fi
        done
    fi
}

# installs munin-pihole-plugins plugins and symbolic links
# plugins to be installed can be configured using PLUGIN_LIST
install_plugins() {
    if [[ -d "$munin_plugin_dir" ]]; then
        if [[ -d "$node_plugin_dir" ]]; then
            output " * \\e[32;1m[INFO]\\e[0m Installing plugin"
            download "$plugin_repo/usr/share/munin/plugins/pihole_" -P "$munin_plugin_dir" || return
            chmod +x "$munin_plugin_dir/pihole_" || return
            output " * \\e[32;1m[INFO]\\e[0m Creating selected plugin links"
            for plugin_id in $plugin_list; do
                ln -s "$munin_plugin_dir/pihole_" "$node_plugin_dir/pihole_$plugin_id" || return
                output "   $plugin_id"
            done
        else
            echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin node plugin directory found at
   $node_plugin_dir"
            output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export NODE_PLUGIN_DIR=\"/path/to/directory\""
            exit 1
        fi
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin plugin directory found at
   $munin_plugin_dir"
        output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export MUNIN_PLUGIN_DIR=\"/path/to/directory\""
        exit 1
    fi
}

# installs a default configuration file
# this should not be required but if it does have to be configured it is nicer
# if it already exists
configure_plugins() {
    if [[ -d "$plugin_config_dir" ]]; then
        if [[ ! -f  "$plugin_config_dir/pihole.conf" ]]; then
            download "$plugin_repo/etc/munin/plugin-conf.d/pihole.conf" -P "$plugin_config_dir"
            output " * \\e[32;1m[INFO]\\e[0m Default plugin configuration saved to
   $plugin_config_dir/pihole.conf"
        fi
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin plugin configuration directory found at
   $plugin_config_dir"
        output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export PLUGIN_CONFIG_DIR=\"/path/to/directory\""
        exit 1
    fi
    if [[ "$pihole_on_host" == "no" ]]; then
        output " * \\e[33;1m[WARNING]\\e[0m The Pi-hole® command 'pihole' was not found on this host
   If this was intentional you will need to edit
   $plugin_config_dir/pihole.conf
   and replace the host and setupvars values with those of your Pi-hole® host"
    fi
}

# restart relevant services
restart_services() {
    if [[ "$install_plugins" == "true" ]]; then
        service_list+="$plugin_services"
    fi
    if [[ "$install_webserver" == "true" ]]; then
        service_list+="$webserver_services"
    fi
    if [[ -n "$service_list" ]]; then
        if [[ -x "$(command -v service)" ]]; then
            for service_id in $service_list; do
                output " * \\e[32;1m[INFO]\\e[0m Restarting $service_id service"
                service "$service_id" restart
            done
        else
            echo -e " * \\e[31;1m[ERROR]\\e[0m The required command 'service' was not found"
            exit 1
        fi
    fi
}

# installs the munin-pihole-plugins script on the host
# warn the user if script_dir is not in their path and suggest how to add it
install_script() {
    if [[ -d "$script_dir" ]]; then
        if [[ ! -f "$script_dir/munin-pihole-plugins" ]]; then
            download "$plugin_repo/script/munin-pihole-plugins" -P "$script_dir"
            chmod +x "$script_dir/munin-pihole-plugins" || return
            output " * \\e[32;1m[INFO]\\e[0m A copy of the munin-pihole-plugins script was installed to
   $script_dir/munin-pihole-plugins"
        fi
        if [[ ":$PATH:" != *":$script_dir:"* ]]; then
            output " * \\e[33;1m[WARNING]\\e[0m The munin-pihole-plugins script directory
   $script_dir
   is not in your \$PATH variable try
   export PATH=\"\$PATH:$script_dir\""
        fi
    else
        echo -e " * \\e[31;1m[ERROR]\\e[0m No directory found at
   $script_dir"
        output " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try
   export SCRIPT_DIR=\"/path/to/directory\""
        exit 1
    fi
}

# spawns a child script to uninstall a locally installed munin-pihole-plugins
# script if present
uninstall_script() {
            cat > "$TEMP/.munin-pihole-plugins_uninstall" << EOF
#!/usr/bin/env bash

# .munin-pihole-plugins_uninstall
# saint-lascivious (Hayden Pearce) 2022
# saint@sainternet.xyz

# uninstalls a locally installed copy of the munin-pihole-plugins script
uninstall_now() {
    rm "$script_dir/munin-pihole-plugins" || return
    echo -e " * \\e[32;1m[INFO]\\e[0m Done"
}

uninstall_now
EOF
    chmod +x "$TEMP/.munin-pihole-plugins_uninstall"
    exec /bin/bash "$TEMP/.munin-pihole-plugins_uninstall"
}

# an opportunistic pagination wrapper, more or less
some() {
    if [[ "$terminal_height" -lt "$min_height" ]]; then
        if [[ -x "$(command -v less)" ]]; then
            echo -e "$@" | less
        else
            if [[ -x "$(command -v more)" ]]; then
                echo -e "$@" | more
            else
                echo -e "$@"
            fi
        fi
    else
        echo -e "$@"
    fi
}

# check the version reported by munin-pihole-plugins.sainternet.xyz
# nslookup, as far as i am aware, has no analogue to dig's +short, so it
# requires a bunch of additional bullshit to strip the version from the txt
# record
# why tail 9, when we want 8 characters? fun fact: echo appends a newline
check_version() {
    version_domain="munin-pihole-plugins.sainternet.xyz"
    if [[ -x "$(command -v dig)" ]]; then
        version_query="$(dig txt +short +timeout=5 +tries=2 "$version_domain" @"$dns_server" -p "$dns_port" | sed s'/[^0-9.]//g')"
    else
        if [[ -x "$(command -v nslookup)" ]]; then
            version_query="$(nslookup -port="$dns_port" -retry=2 -timeout=5 -type=txt "$version_domain" "$dns_server" | grep '"version: [0-9].[0-9].[0-9]"' | sed s'/[^0-9.]//g' | tail -c 9)"
        fi
    fi
    if [[ -n "$version_query" ]]; then
        remote_version="$version_query"
    fi
}

# display munin-pihole-plugins script help text
# height is the minimal terminal height required to display the full output
# in an 80 character wide terminal
help_function() {
    case "${2}" in
        "-h" | "--help" | "help"                    )
            min_height="7"
            some "Usage: munin-pihole-plugins $2
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -h\\t\\t--help\\t\\t\\tDisplay this help dialogue
\\nDisplay munin-pihole-plugins help information." ;;
        "-i" | "--install" | "install"              )
            min_height="29"
            some "Usage: munin-pihole-plugins {$2 [PARAMETER]}
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -i\\t\\t--install\\t\\tInstall munin-pihole-plugins
\\nInstall and configure Munin monitoring server software (default: true), client
software (default: true), selected munin-pihole-plugins plugins (default: all)
and install a copy of the munin-pihole-plugins script (default: true) to a
selected directory (default: /usr/local/bin).
\\nThe munin-pihole-plugins script will self update (default: true) before install
if a newer version of the munin-pihole-plugins script is available.
\\nYou can run the installation again at any time afterwards to update the
munin-pihole-plugins script and plugins, optionally selecting which plugins to
install using the PLUGIN_LIST variable.
\\nTakes an optional parameter 'plugins', 'script', or 'webserver' to install
only that component respectively.
\\nParameter\\t\\t\\t\\tFunction
 -p, plugins, --plugins\\t\\t\\tInstall and configure munin-node, and
\\t\\t\\t\\t\\tmunin-pihole-plugins plugins
 -s, script, --script\\t\\t\\tInstall the munin-pihole-plugins script
 -w, webserver, --webserver\\t\\tInstall and configure munin, lighttpd
\\t\\t\\t\\t\\tand lighttpd-external-munin-proxy
\\nExample: 'munin-pihole-plugins $2 --plugins'" ;;
        "-v" | "--version" | "version"              )
            min_height="10"
            some "Usage: munin-pihole-plugins {$2}
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -v\\t\\t--version\\t\\tDisplay the current and latest versions
\\nDisplay the current munin-pihole-plugins script version, and compare it to
the latest munin-pihole-plugins script version.
\\nAn additional notification will be displayed if an update is available." ;;
        "-U" | "--uninstall" | "uninstall"          )
            min_height="21"
            some "Usage: munin-pihole-plugins {$2 [PARAMETER]}
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -U\\t\\t--uninstall\\t\\tUninstall munin-pihole-plugins
\\nCompletely uninstall munin-pihole-plugins, you will be asked if you want to
uninstall any dependencies that munin-pihole-plugins may have installed.
\\nTakes an optional parameter 'plugins', 'script', or 'webserver' to uninstall
only that component respectively.
\\nParameter\\t\\t\\t\\tFunction
 -p, plugins, --plugins\\t\\t\\tUninstall munin-node, and
\\t\\t\\t\\t\\tmunin-pihole-plugins plugins
 -s, script, --script\\t\\t\\tUninstall the munin-pihole-plugins
\\t\\t\\t\\t\\tscript
 -w, webserver, --webserver\\t\\tUninstall munin, lighttpd, and
\\t\\t\\t\\t\\tlighttpd-external-munin-proxy
\\nExample: 'munin-pihole-plugins $2 --script'" ;;
        "-V" | "--variables" | "variables"          )
            min_height="9"
            some "Usage: munin-pihole-plugins {$2}
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -V\\t\\t--variables\\t\\tDisplay environment variables
\\nDisplay a full list of environment variables used by the munin-pihole-plugins
script, and their current values. The variables can be used to customize
various aspects of the munin-pihole-plugins script's operation." ;;
        *                                           )
            min_height="12"
            some "Usage: munin-pihole-plugins {OPTION [PARAMETER]}
\\nOption\\t\\tGNU long option\\t\\tMeaning
 -h\\t\\t--help\\t\\t\\tDisplay this help dialogue
 -i\\t\\t--install\\t\\tInstall munin-pihole-plugins
 -v\\t\\t--version\\t\\tDisplay the current and latest versions
 -U\\t\\t--uninstall\\t\\tUninstall munin-pihole-plugins
 -V\\t\\t--variables\\t\\tDisplay environment variables
\\nUse '$1 {OPTION}' for more detailed explanations of each command
Example: 'munin-pihole-plugins $1 --install'" ;;
    esac
}

# primary installation function, installation exceptions are handled here
install_function() {
    case "${2}" in
        "-p" | "plugins" | "--plugins"              )
             exec env INSTALL_SCRIPT="false" INSTALL_WEBSERVER="false" /bin/bash "$0" "$1" ;;
        "-P" | "plugins-only" | "--plugins-only"    )
             exec env INSTALL_SCRIPT="false" INSTALL_WEBSERVER="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        "-s" | "script" | "--script"                )
             exec env INSTALL_PLUGINS="false" INSTALL_WEBSERVER="false" /bin/bash "$0" "$1" ;;
        "-S" | "script-only" | "--script-only"      )
             exec env INSTALL_PLUGINS="false" INSTALL_WEBSERVER="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        "-w" | "webserver" | "--webserver"          )
             exec env INSTALL_PLUGINS="false" INSTALL_SCRIPT="false" /bin/bash "$0" "$1" ;;
        "-W" | "webserver-only" | "--webserver-only")
             exec env INSTALL_PLUGINS="false" INSTALL_SCRIPT="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        *                                           )
            if [[ ! "$install_plugins" == "true" ]] && [[ ! "$install_script" == "true" ]] && [[ ! "$install_webserver" == "true" ]]; then
                echo -e " * \\e[31;1m[ERROR]\\e[0m No action(s) to perform
   At least one INSTALL_* variable must be \"true\""
                exit 1
            fi
            check_privilege "$@"
            check_version
            if [[ "$update_self" == "true" ]]; then
                if [[ -f "$TEMP/.munin-pihole-plugins" ]]; then
                    rm "$TEMP/.munin-pihole-plugins" || return
                fi
                if [[ "$remote_version" > "$VERSION" ]]; then
                    update_script "$@"
                fi
            fi
            obnoxious_header
            if [[ "$skip_dependency_check" == "false" ]]; then
                install_dependencies
            else
                output " * \\e[32;1m[INFO]\\e[0m Skipping dependency checks"
            fi
            if [[ "$install_plugins" == "true" ]]; then
                if [[ -n "$plugin_list" ]]; then
                    uninstall_plugins
                    install_plugins
                    check_pihole
                    configure_plugins
                else
                    echo -e " * \\e[31;1m[ERROR]\\e[0m No action(s) to perform
   No plugins in PLUGIN_LIST"
                    exit 1
                fi
            else
                output " * \\e[32;1m[INFO]\\e[0m Skipping plugin installation"
            fi
            if [[ "$install_webserver" == "true" ]]; then
                configure_proxy
                configure_munin
            else
                output " * \\e[32;1m[INFO]\\e[0m Skipping webserver installation"
            fi
            restart_services
            if [[ "$install_script" == "true" ]]; then
                install_script
            else
                output " * \\e[32;1m[INFO]\\e[0m Skipping script installation"
            fi
            output " * \\e[32;1m[INFO]\\e[0m Done" ;;
    esac
}

# uninstall munin-pihole-plugins
# removes all munin plugins and related configuration placed by
# munin-pihole-plugins and then prompts to remove any dependencies that may
# have been installed by munin-pihole-plugins (since we don't track what we
# did install if anything)
# places a blank external.conf file for lighttpd if we can't restore a backup
# because apparently it will pitch a fit if external.conf doesn't exist
uninstall_function() {
    case "${2}" in
        "-p" | "plugins" | "--plugins"              )
             exec env INSTALL_SCRIPT="false" INSTALL_WEBSERVER="false" /bin/bash "$0" "$1" ;;
        "-P" | "plugins-only" | "--plugins-only"    )
             exec env INSTALL_SCRIPT="false" INSTALL_WEBSERVER="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        "-s" | "script" | "--script"                )
             exec env INSTALL_PLUGINS="false" INSTALL_WEBSERVER="false" /bin/bash "$0" "$1" ;;
        "-S" | "script-only" | "--script-only"      )
             exec env INSTALL_PLUGINS="false" INSTALL_WEBSERVER="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        "-w" | "webserver" | "--webserver"          )
             exec env INSTALL_PLUGINS="false" INSTALL_SCRIPT="false" /bin/bash "$0" "$1" ;;
        "-W" | "webserver-only" | "--webserver-only")
             exec env INSTALL_PLUGINS="false" INSTALL_SCRIPT="false" SKIP_DEPENDENCY_CHECK="true" /bin/bash "$0" "$1" ;;
        *                                           )
            if [[ ! "$install_plugins" == "true" ]] && [[ ! "$install_script" == "true" ]] && [[ ! "$install_webserver" == "true" ]]; then
                echo -e " * \\e[31;1m[ERROR]\\e[0m No action(s) to perform
   At least one INSTALL_* variable must be \"true\""
                exit 1
            fi
            check_privilege "$@"
            obnoxious_header
            if [[ "$install_plugins" == "true" ]]; then
                dependency_list+="$plugin_dependencies"
                if [[ -d "$plugin_config_dir" ]]; then
                    if [[ -f  "$plugin_config_dir/pihole.conf" ]]; then
                        rm "$plugin_config_dir/pihole.conf" || return
                    fi
                fi
                uninstall_plugins
            fi
            if [[ "$install_webserver" == "true" ]]; then
                dependency_list+="$webserver_dependencies"
                if [[ -d "$proxy_config_dir" ]]; then
                    if [[ -f "$proxy_config_dir/external.conf.orig" ]]; then
                        mv "$proxy_config_dir/external.conf.orig" "$proxy_config_dir/external.conf" || return
                        output " * \\e[32;1m[INFO]\\e[0m Original lighttpd external.conf restored from backup"
                    else
                        if [[ -f "$proxy_config_dir/external.conf" ]]; then
                            rm "$proxy_config_dir/external.conf" || return
                            touch "$proxy_config_dir/external.conf" || return
                        fi
                    fi
                fi
                if [[ -d "$munin_config_dir" ]]; then
                    if [[ -f "$munin_config_dir/99-graph-strategy.conf" ]]; then
                        rm "$munin_config_dir/99-graph-strategy.conf" || return
                    fi
                else
                    if [[ -d "$munin_dir" ]]; then
                        if [[ -f "$munin_dir/munin.conf" ]]; then
                            sed -i "s/^html_strategy cli/#html_strategy cron/g" "$munin_dir/munin.conf" || return
                            sed -i "s/^graph_strategy cli/#graph_strategy cron/g" "$munin_dir/munin.conf" || return
                        fi
                    fi
                fi

            fi
            if [[ "$skip_dependency_check" == "false" ]]; then
                if [[ -x "$(command -v dpkg-query)" ]]; then
                    if [[ -x "$(command -v apt)" ]]; then
                        for dependency_id in $dependency_list; do
                            package_query="$(dpkg-query -W --showformat='${Status}\n' "$dependency_id" | grep "install ok installed")"
                            if [[ -n "$package_query" ]]; then
                                output " * \\e[33;1m[WARNING]\\e[0m $dependency_id may have been installed by munin-pihole-plugins
   Would you like to uninstall $dependency_id now?"
                                if [[ "$dependency_id" == "init-system-helpers" ]] || [[ "$dependency_id" == "wget" ]]; then
                                    output " * \\e[32;1m[INFO]\\e[0m It probably wasn't, and you probably wouldn't"
                                fi
                                apt remove "$dependency_id"
                            fi
                        done
                    fi
                fi
            fi
            if [[ "$install_script" == "true" ]]; then
                dependency_list+="$script_dependencies"
                if [[ -d "$script_dir" ]]; then
                    if [[ -f "$script_dir/munin-pihole-plugins" ]]; then
                        uninstall_script
                    fi
                fi
            else
                output " * \\e[32;1m[INFO]\\e[0m Done"
            fi ;;
    esac
}

# display the current and latest munin-pihole-plugins script versions
version_function() {
    check_version
    if [[ -n "$remote_version" ]]; then
        if [[ "$remote_version" > "$VERSION" ]]; then
            min_height="3"
            some " * \\e[32;1m[INFO]\\e[0m An update for munin-pihole-plugins is available
munin-pihole-plugins version is v$VERSION (Latest: v$remote_version)"
        else
            some "munin-pihole-plugins version is v$VERSION (Latest: v$remote_version)"
        fi
    else
        min_height="4"
        some " * \\e[33;1m[WARNING]\\e[0m Unable to locate a TXT record for
   $version_domain
   using the nameserver $dns_server on port $dns_port
munin-pihole-plugins version is v$VERSION (Latest: unknown)"
    fi
}

# display munin-pihole-plugins environment variables and their current values
# there were too many variables to list in the main help text
# height is the minimal terminal height required to display the full output
# in an 80 character wide terminal
variable_function() {
    min_height="21"
    some "Usage: export [VARIABLE]=\"value\"
\\nVariable
  DNS_PORT=\"$dns_port\"
  DNS_SERVER=\"$dns_server\"
  INSTALL_PLUGINS=\"$install_plugins\"
  INSTALL_SCRIPT=\"$install_script\"
  INSTALL_WEBSERVER=\"$install_webserver\"
  MUNIN_DIR=\"$munin_dir\"
  MUNIN_CONFIG_DIR=\"$munin_config_dir\"
  MUNIN_PLUGIN_DIR=\"$munin_plugin_dir\"
  NODE_PLUGIN_DIR=\"$node_plugin_dir\"
  PLUGIN_CONFIG_DIR=\"$plugin_config_dir\"
  PLUGIN_LIST=\"$plugin_list\"
  PROXY_CONFIG_DIR=\"$proxy_config_dir\"
  SCRIPT_DIR=\"$script_dir\"
  SKIP_DEPENDENCY_CHECK=\"$skip_dependency_check\"
  UPDATE_SELF=\"$update_self\"
  VERBOSE_OUTPUT=\"$verbose_output\""
}

# handle invalid input by prompting on how to find valid input
# height is the minimal terminal height required to display the full output
# in an 80 character wide terminal
mini_help_function() {
    min_height="3"
    some "munin-pihole-plugins: unrecognized option '$1'
Type 'munin-pihole-plugins -h' for a list of available options"
}

# not so simple input handler
# i hate having to do this but i realised i kinda fucked myself and dig ended
# up quietly being a hard dependency without my noticing it this weird
# guarding  of install and version is temporary, hopefully
input_handler() {
    case "${1}" in
        "-h" | "--help" | "help"                    )
            help_function "$@" ;;
        "-i" | "--install" | "install"              )
            install_function "$@" ;;
        "-v" | "--version" | "version"              )
            version_function "$@" ;;
        "-U" | "--uninstall" | "uninstall"          )
            uninstall_function "$@" ;;
        "-V" | "--variables" | "variables"          )
            variable_function ;;
        *                                           )
            mini_help_function "$@" ;;
    esac
}

input_handler "$@"
